services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6378:6379"