version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6378:6379"


  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566" # aws server gateway
      - "4510-4559:4510-4559"
    environment:
      SERVICES: s3
      DEBUG: 1
    volumes:
      - "./data/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"