// Code generated by mockery. DO NOT EDIT.

package utility

import mock "github.com/stretchr/testify/mock"

// MockPasswordUtil is an autogenerated mock type for the PasswordUtil type
type MockPasswordUtil struct {
	mock.Mock
}

type MockPasswordUtil_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordUtil) EXPECT() *MockPasswordUtil_Expecter {
	return &MockPasswordUtil_Expecter{mock: &_m.Mock}
}

// CheckPasswordHash provides a mock function with given fields: password, hash
func (_m *MockPasswordUtil) CheckPasswordHash(password string, hash string) bool {
	ret := _m.Called(password, hash)

	if len(ret) == 0 {
		panic("no return value specified for CheckPasswordHash")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(password, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockPasswordUtil_CheckPasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPasswordHash'
type MockPasswordUtil_CheckPasswordHash_Call struct {
	*mock.Call
}

// CheckPasswordHash is a helper method to define mock.On call
//   - password string
//   - hash string
func (_e *MockPasswordUtil_Expecter) CheckPasswordHash(password interface{}, hash interface{}) *MockPasswordUtil_CheckPasswordHash_Call {
	return &MockPasswordUtil_CheckPasswordHash_Call{Call: _e.mock.On("CheckPasswordHash", password, hash)}
}

func (_c *MockPasswordUtil_CheckPasswordHash_Call) Run(run func(password string, hash string)) *MockPasswordUtil_CheckPasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordUtil_CheckPasswordHash_Call) Return(_a0 bool) *MockPasswordUtil_CheckPasswordHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordUtil_CheckPasswordHash_Call) RunAndReturn(run func(string, string) bool) *MockPasswordUtil_CheckPasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function with given fields: password
func (_m *MockPasswordUtil) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordUtil_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockPasswordUtil_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordUtil_Expecter) HashPassword(password interface{}) *MockPasswordUtil_HashPassword_Call {
	return &MockPasswordUtil_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockPasswordUtil_HashPassword_Call) Run(run func(password string)) *MockPasswordUtil_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPasswordUtil_HashPassword_Call) Return(_a0 string, _a1 error) *MockPasswordUtil_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordUtil_HashPassword_Call) RunAndReturn(run func(string) (string, error)) *MockPasswordUtil_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordUtil creates a new instance of MockPasswordUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordUtil(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordUtil {
	mock := &MockPasswordUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
